[theme]
primaryColor = "#83A598"        # verde claro
backgroundColor = "#282828"     # fundo escuro
secondaryBackgroundColor = "#3C3836"  # fundo secundário
textColor = "#EBDBB2"           # texto claro
font = "sans serif"

[server]
headless = true
enableStaticServing = true
